# Generated by Django 3.2.8 on 2021-10-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211030_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_doctor',
            field=models.BooleanField(default=False, verbose_name='Is a Doctor'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_labop',
            field=models.BooleanField(default=False, verbose_name='Is a Lab Operator'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
