# Generated by Django 3.2.8 on 2021-11-01 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lab_operator.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Radiological_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment_name', models.CharField(max_length=200, verbose_name='Experiment Name')),
                ('patient_history', models.CharField(max_length=10000, verbose_name='Patient History')),
                ('procedure', models.CharField(max_length=10000, verbose_name='Experiment Procedure')),
                ('findings', models.CharField(max_length=10000, verbose_name='Findings')),
                ('impression', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Impression')),
                ('file', models.FileField(upload_to=lab_operator.models.user_directory_path)),
                ('upload_date', models.DateField(default='2021-11-01', editable=False)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_by_operator', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_of_patient', to=settings.AUTH_USER_MODEL, verbose_name='Patient Assigned')),
            ],
        ),
    ]
