# Generated by Django 3.2.8 on 2021-11-02 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_operator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiological_data',
            name='upload_date',
            field=models.DateField(default='2021-11-02', editable=False),
        ),
    ]
