# Generated by Django 3.2.8 on 2021-10-31 12:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 31, 12, 11, 30, 602461, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='follow_up_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 31, 12, 11, 48, 242929, tzinfo=utc), verbose_name='Date for Follow Up'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='symptoms',
            field=models.CharField(default='test', max_length=10000, verbose_name='Symptoms Found'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='tests_given',
            field=models.CharField(default='test', max_length=10000, verbose_name='Tests given'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='treatment',
            field=models.CharField(default='test', max_length=10000, verbose_name='Treatment Given'),
            preserve_default=False,
        ),
    ]
