# Generated by Django 3.2.8 on 2021-10-31 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor', '0004_auto_20211031_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Prescription_By_Doctor', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Doctor'),
        ),
    ]
