# Generated by Django 3.2.8 on 2021-11-02 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_alter_prescription_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='follow_up_date',
            field=models.DateField(help_text='Please enter in YYYY-MM-DD format', verbose_name='Date for Follow Up'),
        ),
    ]
